- planex.spec
- planex-specdep is now known as planex-depend
- planex-depend: By default, produce packages for the host system
- planex-depend: Add a --topdir parameter to set rpmbuild working directory
- planex-depend, planex-configure: Package name checking is now optional
- planex-configure: SRPM building is now optional
- planex-clone, planex-configure: Default configuration directory is now '.'
- planex-cache: Support multiple cache locations
- planex-depend: Add support for git:// and hg:// source URLs
- Add Makefile.common, containing useful generic make rules
> planex: Release 0.6.0

- debian/control
> debian/control: Add runtime dependency on python-setuptools

- planex/fetch.py
Some sites reject the useragent set by PyCURL.   Fixes #126.
> fetch: Set a custom useragent string

- planex/Makefile.rules
- planex/fetch.py
The make pattern rule which calls fetch only fires once, even if the
rule defines multiple targets.   Make does not provide a variable to
access all the targets, only the one which happened to be the first to
need to be rebuilt.   To handle a spec file which needs several sources
we must download all of them in one invocation of fetch.
Fixes #130.
> fetch: Download all sources defined in the spec file

- planex/depend.py
It's ugly to have to invert the value of the 'no-package-name-check'
before passing it to Spec.  Change the definition of the --no-package-name-check
command-line flag so that this is not necessary.
> depend: Remove ugly handling of 'no-package-name-check' argument

- planex-demo/mock/default.cfg.in
- planex/cache.py
- planex/globals.py
Most examples show this loopback repository being called 'mock',
but we can override that if needed.
Fixes #158 
> cache: Add flag for mock loopback repo name, default to 'mock'

- planex/fetch.py
This matches the logging policy in the other planex modules.
> fetch: Log at 'debug' rather than 'info' level

- planex/Makefile.rules
We now create a symlink from SRPMS to _build/SRPMS.   The
clean target should remove it.
> Makefile.rules: Clean the SRPMS symlink

- planex/Makefile.rules
There is an undiagnosed race between createrepo and planex-cache
in concurrent builds.   Ordinary mock is not affected.
> Makefile.rules: Disable planex-cache by default

- planex/cache.py
> cache: Don't re-use yum's cachedir in /tmp - causes clashes between concurrent jobs

- planex/cache.py
- planex/util.py
We print mock's stderr and stdout if it fails, but the most useful
information for debugging a mock failure is often in the root.log
and build.log files.    Print these as well.
> cache: Print mock's logs if it fails

- planex/cache.py
Update a cached file's access and modification timestamps when we use it.
This makes it easier to clear old, unused files out of the cache.
> cache: Update cached files' timestamps on cache hits

- planex.spec
We set the priority of the loopback repository such that it overrides the base system repository.  Without this plugin, priority assignments in yum.conf.d are ignored.
> Depend on yum-plugin-priorities

- planex/cache.py
planex-cache can fail if another racing build writes a binary RPM to the
cache between the time when cache checks the cache and tries to write
back to it after building the package.   If the package is already in the
cache, we can just throw away our local build.
Fixes #238.
> planex-cache: Don't fail if the binary package is already in the cache

- planex/Makefile.rules
Major mode is determined from the first non-blank line, see
https://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html
> Move Emacs mode line to top of file

- planex/cache.py
Mock should be run by a normal user account calling /usr/bin/mock.
If the user's path causes /usr/sbin/mock to be picked up instead,
it will exit with a warning but with a 0 exit code.
Subprocess.Popen will not detect this as an error and the build will
appear to succeed without building anything.
> cache: Make sure we call /usr/bin/mock instead of /usr/sbin/mock

- planex/Makefile.rules
Non-local specfiles could be retrieved from elsewhere, extend ALLSPECS
with spcecfiles from those under revision control and derived from
pins.
Also cleanup the dependencies of $(DEPS).
> Introduce ALLSPECS

- planex/makesrpm.py
Exit with error message when no component specfile given as parameter to planex-make-srpm.
> mksrpm: handle missing arguments

- planex.spec
- setup.py
Installing files to /etc in setup.py breaks virtualenv
> packaging: Do not install Bash completion file through setuptools

- planex/makesrpm.py
Bitbucket generates source archives without a directory, adjust
%autosetup accordingly.
> makesrpm: handle sources with no top-level directory

- planex/makesrpm.py
Add option to retain the directory containing the autogenerated
specfile.
> makesrpm: add --keeptmp

- planex/depend.py
The dependency recipes are more readable if editors are informed that
the content of the file is a Makefile.
> depend: add Emacs and vim mode line

- planex/makesrpm.py
- tests/test_makesrpm.py
Add a guard parameter to parse_patchseries() and use it to select
guarded patches. No caller defines it yet so it causes no positive
guards and all negative guards to be applied.
> makesrpm: add initial support for patch guards

- planex/Makefile.rules
Make the dependency rules refer to $(TOPDIR)/SPECS rather than SPECS,
at present the directories are symlinked but this will cope with
$(TOPDIR)/SPECS containing links and/or real specfiles.
> Generate dependencies from $(TOPDIR)/SPECS

- planex/extract.py
- tests/test_extract.py
Patches many not be named uniquely and are all currently written to
SOURCES. Add a prefix to disambiguate them.
> extract: prefix patches with package name

- planex/fetch.py
> fetch: Only parse specfile once per run, not once per requested source

- planex/Makefile.rules
- planex/extract.py
- planex/fetch.py
- planex/makesrpm.py
This fix will correctly return the topdir of a tarball (if any). Without this fix the code would return an incorrect result in situations in which all the files in the tarball have a common prefix but they are not stored in any topdir.
> Correctly return topdir of tarball

- planex/Makefile.rules
- planex/extract.py
- planex/makesrpm.py
- planex/spec.py
- tests/test_depend.py
- tests/test_spec.py
Use per-package directories under SOURCES to store source files.  This removes the risk of name collisions between patches for different packages.
> Per package sourcedirs

- planex/Makefile.rules
In order to make re-writing spec files easier break the link between
SPECS and _build/SPECS. Add a temporary pattern rule to link
individual spec files.
> Makefile.rules: make _build/SPECS a directory

- planex/spec.py
The rpm bindings complain to stderr that sources do not exist. This is
expected in some use cases, e.g. when generating the dependency file.
Temporarily redirect stderr to /dev/null while parsing the spec file.
> spec: silence errors about missing sources

- planex/depend.py
Generate a target of the form of <spec>.srpm for each specfile
> depend: Generate short names for SRPMS

- planex/Makefile.rules
- planex/spec.py
- tests/test_depend.py
- tests/test_spec.py
Remove the hard coded _sourcedir from spec and add a variable
in Makefile.rules which can be used to override it instead.
> spec, Makefile.rules: Don't unconditionally override _sourcedir

- planex.spec
Install Makefile.rules to /usr/share/planex for backwards compatibility
with older Planex builds.
> spec: Install Makefile.rules to /usr/share/planex

- planex/util.py
Hashing file contents is expensive and unnecessary if the files are of
different lengths. Check the file sizes first and only hash them if they
are the same.
Signed-off-by: Simon J. Rowe <srowe@mose.org.uk>
> util: test file sizes before hashing

- planex/clonesources.py
- setup.py
Move clone.py to clonesources.py so the top-level script can be called
planex-clone.
> planex-clone-sources: rename clone tool

- planex/Makefile.rules
- planex/mock.py
- setup.py
This PR introduces `planex-build-mock`. For the moment it is just wrapper around `mock`.
It has been tested by successfully rebuilding the `baggage` repo.
> [CP-17919] Add a wrapper around mock

- docker/entry.sh
Using the -c option runs the command without a controlling tty.  If no
arguments are specified, run an interactive shell that will have job
control etc.
> planex-container: allow running an interactive shell

- Dockerfile
- docker/Dockerfile.release
- docker/Dockerfile.unstable
- docker/entry.sh
Running the "usermod" command to change the uid of a user has the side
effect of changing the uid in all files in the home of the user to match
the new uid.
When ran in a directory having a large number of files on a slow fs (NFS)
it can take awfully long time.
The planex docker image uses usermod to set up the "build" user inside the
container with a right uid, so it has the issue described above.
With this change the "build" user is created with the right uid in the
first place, so "usermod" is not needed, thus fixing the performance issue.
Signed-off-by: Istvan Szekeres <istvan.szekeres@citrix.com>
> Docker: change "build" user creation to avoid scanning large directories

- planex/Makefile.rules
- planex/depend.py
- planex/extract.py
- planex/manifest.py
- planex/repository.py
- planex/util.py
- setup.py
- tests/data/bitbucket-repo.json
- tests/data/github-repo.json
- tests/data/gitweb-repo.json
- tests/data/manifest/blktap.json
- tests/data/manifest/blktap.lnk
- tests/data/manifest/blktap.spec
- tests/data/manifest/branding-xenserver.json
- tests/data/manifest/branding-xenserver.spec
- tests/data/manifest/git_ls_remote_out.json
- tests/data/manifest/vhostmd.json
- tests/data/manifest/vhostmd.lnk
- tests/data/manifest/vhostmd.spec
- tests/test_bitbucket_repository.py
- tests/test_depend.py
- tests/test_github_repository.py
- tests/test_gitweb_repository.py
- tests/test_manifest.py
planex-manifest is a command line tool that prints a manifest
in stdout, given a package's spec and lnk (if applicable) files.
A package's SRPM now depends on its manifest file and
a manifest file now depends on its package's spec/lnk files.
Signed-off-by: Kostas Ladopoulos <konstantinos.ladopoulos@citrix.com>
> CP-19321: Add planex-manifest tool

- planex/repository.py
- tests/data/bitbucket-repo.json
Fix the parsing of the query string when it does not start with
'refs/...'.
> repository: handle BitBucket URLs with hashes

- planex/Makefile.rules
If the deps file cannot be created or updated, we can't proceed with
the build.   We still use the -include directive for pindeps because
rebuilding it is optional - there might not be any pinned packages in
the repository.
> Makefile.rules: Fail if deps can't be rebuilt

- planex/extract.py
- tests/test_extract.py
This is no longer required as patches are extracted into
per-package source subdirectories.
> extract: Don't prepend package name to patch filename

- planex.spec
- planex/repository.py
- requirements.txt
- tests/data/bitbucket-repo.json
- tests/test_bitbucket_repository.py
This change adds support for converting git 'commitish' references in to a full SHA1 using the BitBucket API. This allows partial sha1's to be specified in a spec / lnk file, and the manifest generation to resolve them to full references.
Unit tests updated to cover this scenario, and tested in a local container.
Note adds a requirement for python-requests - spec file updated to cover this.
> CA-228222 Handle commitish references with BitBucket

- planex/Makefile.rules
- planex/depend.py
- planex/extract.py
- planex/makesrpm.py
- tests/test_depend.py
- The top level SOURCES directory is no longer symlinked in to _build, so source tarballs downloaded by planex-fetch are no longer mixed up with sources which come from the spec file repository.
- patchqueues are no longer unpacked into SOURCES, removing the possibility of stale patches being left over from previous builds
- All spec file manipulation now happens in planex-make-srpm's working directory.   The spec file in the SRPM is rewritten to include patches and to handle top level tarball directories which don't match rpmbuild's expectaitions.   The spec file in _build/SPECS is extracted from the patch queue unaltered and is only used by planex-depend.   planex-extract no longer rewrites files as it extracts them.
> Rewrite linking to centralize all patch queue handling and rewriting in planex-make-srpm

- planex/depend.py
- planex/extract.py
- planex/fetch.py
- planex/makesrpm.py
--topdir and --dist have been replaced by passing rpmbuild-style --define parameters directly
> Remove obsolete --topdir and --dist flags

- planex/manifest.py
- planex/repository.py
Initialize logging so that --debug works. Also report the URL being
used to retrieve the SHA1 in repository.commitish_to_sha1_bitbucket().
> manifest: set up logging

- planex/Makefile.rules
This is needed by the linux-guest-loader package.
> CP-18094: Fetch *.cpio Source archives

- planex/Makefile.rules
$^ expands to all prerequisites, which confuses cp if
the target has several prerequisites.
> Makefile.rules: Use correct implicit variable in copy

- planex/spec.py
We set _specsdir to the directory part of the spec path,
then join the basename of the spec path back with _specsdir,
which is essentially a no-op.   Remove this, and the specsdir
method which is now unused.
> spec: Remove redundant specsdir parameter and accessor

- planex/cmd/makesrpm.py
- planex/cmd/mock.py
- planex/cmd/patchqueue.py
This makes it easier to tell if a utility is leaking temporary directories.
> makesrpm, mock, patchqueue: Use identifiable prefixes for temporary directories

- planex/Makefile.rules
- planex/cmd/clone.py
- planex/cmd/patchqueue.py
- setup.py
This utility will replace the existing planex-clone-sources script.
The existing script tries clones repositories with patch queues, parsing
the tarball HTTP URLs in specs and links, constructing appropriate Git
URLs and fetching them.   The new script only clones pinned repositories -
generating new pin configurations will be handle by a separate script.
The new script adds the ability to print a fragment of Groovy code which
can be included in a Jenkinsfile to tell Jenkins to monitor and fetch a
pinned repository automatically.
This work allows us to set up Jenkins CI jobs for working branches and
have Jenkins build new changes automatically as they are pushed to 
pinned repositories.
> Initial version of new clone sources script which supports Jenkins CI

- planex/cmd/mock.py
Rework subprocess handling in the planex-build-mock command in preparation for adding --init and --cleanup options.
> Rework mock subprocesses

- planex/Makefile.rules
- planex/cmd/mock.py
When mock is first run, it builds a chroot image by downloading
and installing the RPMs specified in the 'chroot_setup_command' in
mock/default.cfg and saving the image as a tarball.   If several mock runs
are started at the same time and no root cache exists, they will all start
building one and will overwrite each others' tarballs as they complete.
This can lead to the root tarball being regenerated several times in the
early phase of a concurrent build.  To avoid this, we can call 'mock
init' before starting the build.  This populates the root cache once,
and the actual build jobs all use this cache rather than rebuilding it.
> Add option to pre-warm the mock cache before building

- planex/patchqueue.py
- tests/data/manifest/branding-xenserver.spec
- tests/test_patchqueue.py
When adding patch lines (e.g. Patch0 etc), planex assumes that they will be applied by rpm, but this is reliant on having a %autosetup with a -p1 argument in your %prep section.
This change verifies this assumption and raises an exception if it's not the case.
> Add a check that a spec has %autosetup with a -p1 argument when applying patches

- planex/cmd/mock.py
Log inside docker with concurrent builds and --output-sync=target
> Pass --verbose if --quiet is not supplied so that logs are produced

- planex/cmd/clone.py
- requirements.txt
* Make `planex-clone` handle structured branch names containing slashes.   This is needed for patchqueues, where the patchqueue must appear in a subdirectory matching the current branch name under .git/patches
* Make `planex-clone` create local branches when the upstream commitish does not point to a branch.
> Planex clone improvements

- docker/planex-container
planex-container is the wrapper script which starts the Planex Docker
container, ensuring that the local working directory and any caches
are mounted into the container properly.   As with entry, this script
is becoming more complicated and translating it to Python gives us
better tools for handling this complexity.
> Docker: Rewrite planex-container script in Python

- docker/entry
- docker/planex-container
If SSH_AUTH_SOCK is defined in the shell which runs planex-container,
mount the file which it points to into the container and pass through
the variable.   Inside the container, the entry script will pass the
environment variable through to the final shell.   This makes it possible to
clone Git repositories over SSH from within the container.
> Pass through SSH_AUTH_SOCK, if defined

- planex/cmd/fetch.py
This can happen when a spec file has multiple sources to be fetched.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> fetch: Fix a TOCTOU race when creating directories

- planex/Makefile.rules
Make the mock config file an explicit dependency of $(RPMS) so that
they are rebuilt if it changes. It also allows the main makefile to
define a rule to generate the mock config.
> Makefile.rules: add a dependency on the mock config

- planex/cmd/clone.py
planex-clone currently exits if the destination directory for a repository already exists or the patchqueue is empty.   In the first case we should continue cloning other pins;  in the second case we should not fail when pushing an empty patchqueue.
> clone: Handle non-fatal errors more gracefully

- planex/cmd/createmockconfig.py
- setup.py
This tool creates a chroot configuration using a reference file and a
set of repositories that are defined in the yum configuration.
> planex-create-mock-config: populate mock repos from yum config

- planex/cmd/makesrpm.py
- planex/tarball.py
GitWeb synthetic tarballs do not unpack into a top level directory with
the name RPM expects.   To work around this, we rewrite %autosetup rules
in spec files.   GitHub generates tarballs which are acceptable to RPM
by default and BitBucket allows the top level directory name to be
specified in the tarball URL, so this rewrite is no longer required.
> makesrpm: Do not rewrite %autosetup rules in spec files

- tests/test_spec.py
- tests/test_tarball.py
This function asserts that two lists contain the same elements, ignoring
element order.
> tests: Use assertItemsEqual() to compare lists

- test-requirements.txt
- tests/__init__.py
- tests/strategies.py
- tests/test_patchqueue.py
This pull request adds some Hypothesis property-based tests for patchqueue guard handling.  Guard handling was already tested by point test in test_patchqueues.py so coverage reported by nosetests does not change, but the property-based tests explore some corner cases which the point test does not.
> Patchqueue property tests

- planex/cmd/args.py
- planex/cmd/createmockconfig.py
- planex/cmd/depend.py
- planex/cmd/extract.py
- planex/cmd/fetch.py
- planex/cmd/init.py
- planex/cmd/makesrpm.py
- planex/cmd/manifest.py
- planex/cmd/mock.py
- planex/cmd/patchqueue.py
- planex/util.py
Move planex.utils.add_common_parser_options into planex.cmd.args
Add an argparse 'type' to handle RPM macro definitions passed using the --define option
> Consolidate argparse

- planex/cmd/depend.py
> depend: Stop disabling pylint's 'too-many-statements' warning

- planex/cmd/depend.py
- tests/test_depend.py
We need to take care when reordering dependencies, as dependencies
appear in variables such as $<, $? and $^ in the order in which they
are declared in the makefile.   Changing the ordering of dependencies
can therefore break tools which use positional parameters.
> depend: Consolidate all manifest-related dependencies in one function

- planex/cmd/depend.py
This argument has not been connected to anything since
5fa3d866f15787d4bef37a4ef37e35e75da0b306
> depend: Remove unused --repos_path argument

- planex/Makefile.rules
The existence of the .DELETE_ON_ERROR target is enough to cause make to
delete any target when the recipe used to produce it fails.   There is
no point in having several declarations of the target with different
prerequisites.
> Makefile.rules: We only need one .DELETE_ON_ERROR target

- planex/Makefile.rules
Append the optional RPMBUILD_EXTRA_FLAGS to RPMBUILD_FLAGS to allow
the caller to add options like --nocheck.
> Makefile.rules: add RPMBUILD_EXTRA_FLAGS

- planex/cmd/depend.py
These conditional statements can only be executed if the earlier
conditional is also executed.   Since the later clauses are subsets
of the earlier one, the current code cannot go wrong when executed;
this commit simply changes the structure of the code to match.
> depend: Fix bad logical code structure

- planex/cmd/patchqueue.py
assemble_extra_sources() takes 'sources' and 'patches' parameters which
are only ever passed the results of calling accessor functions on the
spec object.   Since the spec object is passed to the function as well,
it can call them directly.
> patchqueue: Do not pass parameters which are properties of other parameters

- planex/git.py
git.describe() and git.current_branch()
If we need these in future, we should use [GitPython](http://gitpython.readthedocs.io/en/stable/index.html).
> Remove unused methods

- planex/cmd/createmockconfig.py
'yum.conf' and 'dnf.conf' config options to be defined or overridden.
Signed-off-by: Simon Rowe <simon.rowe@citrix.com>
> create-mock-config: Allow values in the [main] section of the

- planex/cmd/depend.py
If a linked (or pinned )spec file refers to local sources and the link
file provides them, we do not need to print a dependency between the
SRPM and the source because this will be covered by the dependency on
the tarball built from the link.  If the link does not provide sources,
assume that they can be found in the specfile repository.
> depend: Depend on local sources if link/pin does not provide them

- planex/cmd/depend.py
It is valid to set sources to "" in a link file - this means "sources
can be found in the root of the tarball".   Also, some packages have
extra patches in their patchqueues but no extra sources.
> depend: Check patchqueue for sources and patches

- planex/cmd/createmockconfig.py
Allow values in the config_opt['environment'] dictionary to be defined
or overridden from the command line.
> create-mock-config: add --environment argument

- planex/cmd/clone.py
This new option allows the user to avoid cloning the base repository and applying the patchqueue to it.   This can be an expensive operation, and is not necessary if the user does not want to work on the package and instead just wants to build it.
> planex-clone: Add option to skip cloning a patchqueue's base repository

- planex/Makefile.rules
- planex/cmd/manifest.py
This still creates the RPMS and MANIFESTS symlinks, but we plan to drop these in future.
> Makefile.rules: Split up centralized _build/ directory creation

- planex/cmd/pin.py
- planex/repository.py
- setup.py
While cleaning up `planex-pin` to merge back into `planex`, I've realised that there are a few questions that need an answer to proceed.
You can find the code in a monolithic `cmd/pin.py` file in this PR and the issues underlined in `# TODO` comments.
Some of the helpers may be moved to the library, but I will keep them together until I have the final version.
> [WIP] planex-pin: reintroduce to planex

- planex/cmd/createmockconfig.py
If specific packages are included or excluded in a repo carry that on
into the mock config.
> planex-create-mock-config: honour exclude and includepkgs

- setup.py
There is already an explicit map of files to include and defining both
prevents them from being included in a source distribution. See
https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute
> setup.py: remove include_package_data

- planex/cmd/makesrpm.py
When the tarball is created with tar rather than git archive, the
transformations in .gitarchive-info don't get applied.
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
> Don't cause RPM to choke on a malformed gitsha

- planex/Makefile.rules
After 4fc2f628, links were created to the x86_64 and noarch subdirectories
instead of the RPMS directory.
Fixes #457, although in future we would like to remove these symlinks altogether.
> mock: Fix RPMS top-level link

- planex/Makefile.rules
A race can occur when calling ln -sf in older versions of GNU coreutils (and
in busybox):
http://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=commit;h=376967889ed7ed561e46ff6d88a66779db62737a
We seem to be hitting this race because we use ln -sf to create the
RPMS and MANIFESTS top-level symlinks for every target.   Two racing
ln invocations try to remove the existing symlink, one succeeds and the
other fails with the following message:
ln: cannot remove './RPMS': No such file or directory
This does not happen all the time because the first ln may have created
its link, which the second then deletes.
This commit switches back to the previous behaviour of creating these
symlinks at the start of the build.   This has caused problems in the
past (bug 211) so we intend eventually to remove …
> makesrpm: Avoid unlink races in ln -sf

- planex/cmd/depend.py
- planex/spec.py
- tests/test_spec.py
To build package A, mock needs to install all the package's build-time
requirements (BuildRequires). It does not need to install the package's
runtime requirements (Requires). However, to build package B, which
depends on A, mock must install A's runtime requirements. This causes
problems if A's runtime requirements come from the same spec repository as
A itself. planex-depend does not produce a Makefile dependency which will
cause A's runtime dependencies to be build before B is built, so it is
the luck of the draw whether those packages exist at the time B is built.
Technically, planex-depend should make B have a build dependency on
A's runtime dependencies, however it is easier to make A depend on its
own runtime dependencies, even though they are not strictly required in
order to …
> depend: Make a package depend on its Requires as well as its BuildRequires

- planex/cmd/args.py
- planex/cmd/createmockconfig.py
- planex/cmd/depend.py
- planex/cmd/fetch.py
- planex/cmd/init.py
- planex/cmd/makesrpm.py
- planex/cmd/manifest.py
- planex/cmd/mock.py
- planex/cmd/patchqueue.py
- planex/cmd/pin.py
argparse has a 'parents' mechanism which allows parsers to inherit options
from each other.   Use this instead of passing newly-created parsers to
a function which adds common options to them.
> args: Define common argument parsers from which others can inherit

- planex/cmd/depend.py
- planex/cmd/fetch.py
- planex/cmd/makesrpm.py
- planex/cmd/manifest.py
- planex/link.py
- planex/patchqueue.py
- tests/test_link.py
Handle building components that consume pristine source (as specified by the spec), distro patches listed as additional patches in the specfile and local patchqueues.
> Handle building components that have three source

- planex/cmd/makesrpm.py
The variable changeset gets used first as a regex, then becomes the content of
the first successful match.  If the loop hits the continue path, execution
blows up with:
Traceback (most recent call last):
File "/usr/bin/planex-make-srpm", line 9, in <module>
load_entry_point('planex==2.1.1', 'console_scripts', 'planex-make-srpm')()
File "/usr/lib/python2.7/site-packages/planex/cmd/makesrpm.py", line 191, in main
args.sources, args.patchqueue)
File "/usr/lib/python2.7/site-packages/planex/cmd/makesrpm.py", line 146, in populate_working_directory
extract_commit(source, manifests)
File "/usr/lib/python2.7/site-packages/planex/cmd/makesrpm.py", line 129, in extract_commit
manifests[name.strip()] = get_commit_id(archive_info)
File "/usr/lib/python2.7/site-packages/planex/cmd/makesrpm.py", line …
> mksrpm: Fix scoping error in get_commit_id()

- planex/Makefile.rules
- planex/cmd/mock.py
These changes remove the last assumptions that the build outputs will be written somewhere in the spec file repo checkout.   This makes it possible to set TOPDIR to an external path and keep the specs pristine, and may also help with #361.
Fixes #211
> Remove RPMS and MANIFESTS links

- planex/spec.py
* Extract logic to parse spec file quietly
* Inline three single-line helpers which were each used only once
Although the new `parse_spec_quietly()` helper is only used once, it is a substantial piece of code and extracting it simplifies `Spec.__init__()` considerably.
> Refactor helper methods in Spec

- planex/cmd/mock.py
- planex/spec.py
* Extend rpm_macros() context manager to take multiple dicts, removing the need to use OrderedDict.
* Construct SRPM path directly
* Clean up confusion between RPM macros and tags in binary_package_paths()
* Factor out the extraction of NEVRA tag values
> Refactor macro-handling wrappers

- planex/cmd/depend.py
- planex/cmd/fetch.py
- planex/cmd/manifest.py
- planex/cmd/pin.py
- planex/spec.py
- tests/test_spec.py
This pull request consolidates most sources getters into sources() and adds a source() convenience method to fetch the source corresponding to a downloaded file name.
local_sources() and local_patches() remain but will be dealt with in the next pull request.
> Consolidate Spec's various source getter methods

- planex/cmd/depend.py
Rules for sources defined in links were added in the middle of the main dependency generation loop.   The rules covered two distinct cases in one big conditional: adding a dependency from the SRPM on the link, and adding dependencies to download the sources.    These cases belong separately, in two existing functions, so this pull request moves them there.    The order of entries in _build/deps will change a little, but this will have no effect on the build.
> Refactor link-related dependency rule generation

- planex/patchqueue.py
%autosetup is actually a wrapper around %setup and %autopatch, so
%autopatch should also be able to apply patchqueues.
> patchqueue: Apply patchqueues to specs with %autopatch directives

- planex/cmd/makesrpm.py
A spec file can list source files (e.g. source0: ...) and patch
files (e.g. patch0: ...).   If a source or patch has a URL, Planex
can fetch it and pack it into the SRPM;  if the spec only lists
a plain file name, then the file must exist in a subdirectory of
the spec file repository or there must be a link file which tells planex
where to fetch an archive which contains the file.
In the original link format, a single tarball holds the 'extra'
patches and sources, such as service files, along with a single
patchqueue:
```
{
"URL": "https://...#/pkg.patches.tar",
"patches": "SOURCES",
"sources": "PATCHES",
"patchqueue": "PATCHQUEUE"
}
```
"patches", "sources" and "patchqueue" are optional fields - if they
are present they are the subdirectories in which the various types
of files are …
> makesrpm: Fetch sources as well as patches from 'Patch' tarballs

- .travis.yml
Without this, all our dependencies are pulled into the coverage results
> travis.yml: Only include planex in coverage results

- planex/link.py
- planex/spec.py
- tests/test_link.py
The change of the 'patch' name parsing regex to accept zero or more digits
(patch\d*) causes it also to match 'patchqueue'.
> link: Anchor parsing regexes to start and end of keys

- planex/spec.py
A more robust but probably slower solution would be to make
the rpm_macros() wrapper load the Spec back into RPM every
time.   To do this we would have to write it out to a temporary
file and read it back in.
Fixes: #517
> spec: Expand macros in links when loading

- planex/cmd/makesrpm.py
- planex/patchqueue.py
- planex/spec.py
- tests/data/empty.spec
- tests/test_patchqueue.py
- tests/test_spec.py
When rewriting the specs, we delete any Source and Patch entry from the spec file
and we inject:
- first the list of computed sources (link, spec)
- then the list of computed patches (link, spec)
- finally the exploded patchqueues (link).
This should solve #510 and #511
> Rewrite all sources and patches in the spec file

- planex/spec.py
- tests/test_patchqueue.py
This is temporary, until we extens schemaVersion3 to add a ignore-autosetup field (see issue #521)
> Enable check for autosetup/autopatch only for patchqueues 

- planex/spec.py
The rewritten spec files contain lots of duplicated newlines.
This change makes them look more reasonable and prevent issues when commands are split across multiple lines with `\`. 
> spec.py: improve look of rewritten spec files

- planex/spec.py
- tests/data/ocaml-cohttp.lnk
- tests/data/ocaml-cstruct.lnk
- tests/specs/SPECS/PQ.lnk
- tests/specs/SPECS/RP.lnk
This should solve #503 and #515.
~~This PR also introduces a way to delete a source, a patchqueue or a patch by providing an empty record in the link/pin file. I have created #529 to track that as I recall that issue being discussed at a certain point. I am happy to remove the relevant commits if we decide that this is not necessary.~~
EDIT: Removed, it will be part of a separate PR if we decide to stack pins over links
> Refactor schemaVersion to distinguish between 2 and 3, and drop support for 1

- planex/cmd/clone.py
- planex/cmd/manifest.py
- planex/link.py
- planex/spec.py
- tests/data/manifest/blktap.json
- tests/data/manifest/blktap.lnk
- tests/data/manifest/branding-xenserver.json
- tests/data/manifest/vhostmd.json
- tests/data/manifest/vhostmd.lnk
- tests/specs/SPECS/PQ.lnk
- tests/specs/SPECS/RP.lnk
- tests/test_link.py
- tests/test_manifest.py
- tests/test_patchqueue.py
- tests/test_spec.py
This PR removes leftovers of the SchemaVersion:1 parsing, improves the versioning and updates the semantics of the v3 pins.
It also raises an interesting issue with `planex-manifest`, since links v2 it has become completely useless for links and pins.
This should resolve #539 and #540
> Link cleanup

- planex/Makefile.rules
- planex/cmd/clone.py
- planex/cmd/depend.py
- planex/cmd/fetch.py
- planex/cmd/pin.py
- planex/spec.py
This should fix #507 and #533.
The new CLI looks like the following:
```
[planex:master local]$ planex-pin --help
usage: planex-pin [-h] [--quiet] [-v] [--version] [-w | -o OUTPUT]
[--source-override SOURCE] [--patchqueue-override PATCHQUEUE]
PACKAGE
Create a .pin file for PACKAGE. Needs to run from the root of a spec
repository. Note that when URL is an ssh url to a git repository, planex will
first look for a repository with the same name cloned in the $CWD/repos
folder.
positional arguments:
PACKAGE               package name
optional arguments:
-h, --help            show this help message and exit
--quiet, --warn       Only log warnings and errors
-v, --verbose, --debug
Enable debug logging
--version             show program's version number and exit
-w, --write           Write pin …
```
> planex-pin does not know about the new pin format

- planex/cmd/fetch.py
The ObjectTag does not support rev_parse, using hexsha avoids
issues and works for commitish, tags or branches
> fetch.py: make more robust against tags

- planex/spec.py
Although it adds visual noise, the Provides are not inherited and often
we don't even build a main binary package, loosing the manifests data
altogheter. This can also be useful to check consistency in more coherent
ways.
> spec.py: add the manifest to all binary subpackages

- planex/config.py
- tests/test_config.py
Support reading configuration parameters from global, user and local
files.
Fixes #536
> Add a configuration class

- planex/Makefile.rules
planex-depend now consumes the first link/pin file that matches a spec
file. Extend the default wildcards so that the contents of the PINS
directory are picked up first, if present.
> Makefile.rules: include pins in SPECS and LINKS

- planex/cmd/clone.py
If there are no patches or patchqueue the source repo was not being
cloned (unless the --clone argument was used).
> clone: fix cloning of plain repositories

- planex/cmd/clone.py
ee2e21e caused patchqueues to be unexpectedly applied when the
--jenkins argument was used. Drop the mutually exclusive group and
just treat --clone and --jenkins as the simple clone case.
> clone: fix Jenkins/patchqueue interaction

- planex/cmd/clone.py
- requirements.txt
Requiring a pin to contain only repository-backed resources has an
impact on the repositories cloned and monitored by the CI
system. Support, for example, having a https:// URL for the base
repository with an ssh:// URL for a patchqueue.
> clone: implement cloning of non-git resources

- planex/repository.py
A URL query may reference a branch that contains '/' and does not
start with 'heads'.
> repository: fix Bitbucket branch handling

- planex/Makefile.rules
Now that mock configurations are being generated on the fly, the clean
target needs to remove them, to avoid problems when switching
configurations but having old configs lying around.
In addition, when removing them we should be sure to scrub any extant
mock caches and chroots as repository metadata may persist there and
cause problems later.
Since MANIFESTS and RPMS are symbolic links into a location we've just
removed, clean them up also.
> Clean up more things

- planex/cmd/fetch.py
The length of the args array when a RequestException occurs is not
known. If sticking to descriptors inherited from BaseException, it would
be better to use 'message' to avoid an exception while handling the
exception.
> Correct error path on RequestException

- planex/cmd/clone.py
By default when checking out PINS set checkout and poll to true.
This is related to a change to xenserver jenkins pipelines
> In Jenkins checkout add polling/changelog default

- planex/config.py
- planex/repository.py
- tests/test_repository.py
Make the repository manager read the server-type property from the
hosts' section of the config file.
Since the bbtoken code uses ~/.planex as a place to keep its cache, add
~/.planex/planexrc as a search path for the config file, ahead of
~/.planexrc.
Signed-off-by: Tim Smith <tim.smith@citrix.com>
> CA-314309 Allow per-host configuration of repo parsers

- planex/cmd/createmockconfig.py
- tests/test_createmockconfig.py
Since repository priorities are needed to get packages from the
right place, in order for mock builds to work correctly we need to put
the priority information into the mock configuration we generate.
We also need to turn on the priority plugin inside the mock chroot, or
this will not do any good.
While doing this, sort the entries in the mock config by priority and
then by name so that it's easy to grep them out in the right order
later.
> CP-31484 Honor yum repository priorities in mock builds

- planex/cmd/clone.py
- tests/test_createmockconfig.py
*.pin will get passed down to planex-clone if nothing is expanded on the
terminal, just check for wildcards in filenames and exit quietly.
> CA-318284 Wildcard expansion fails internally
