xenserver/planex

- planex.spec
> Spec: Add dist to release number

- planex/Makefile.common
- planex/depend.py
- planex/spec.py
> specdep: Add a --topdir parameter to set the rpmbuild working directory

- planex/util.py
> util: Find the path to the mock package dynamically

- README.md
Signed-off-by: Ravi Pandey <ravi.pandey@citrix.com>
> Adding missing dependencies for installing planex

- planex.spec
> planex.spec: Add runtime dependency on python-setuptools

- planex/cache.py
> cache: Fix pylint warnings

- planex/clone.py
> clone: Fix pylint warnings

- planex/depend.py
> depend: Fix pylint warnings

- planex/build.py
- planex/configure.py
- planex/debianchangelog.py
- planex/debiancontrol.py
- planex/debianmisc.py
- planex/debianrules.py
- planex/depend.py
- planex/downloader.py
- planex/exceptions.py
- planex/makedeb.py
- planex/mappkgname.py
- planex/rpmextra.py
- planex/sources.py
- planex/spec.py
- planex/tree.py
- planex/util.py
All the Python files in the planex/ directory are now PEP8 clean.
> Fix pylint and PEP8 warnings

- tests/test_clone.py
- tests/test_configure.py
- tests/test_depend.py
- tests/test_pkg.py
- tests/test_planex_spec.py
- tests/test_sources.py
> Fix PEP8 warnings in tests

- .travis.yml
- planex/depend.py
- requirements.txt
Currently Travis just runs pep8 over planex/ and tests/
> Set up Travis

- README.md
> README: Add Travis status badge

- planex/cache.py
This also removes a use of global, which triggers a pylint warning.
> cache: Use standard logging instead of DIY

- planex/fetch.py
* Handle https, http and file urls
* Don't try to download local patches and includes
Fixes #131
> Improve url handling in fetch

- .travis.yml
- setup.py
> setup: Fix Pylint and PEP8 warnings

- planex/pin.py
> pin: Fix typo in help

- planex/cache.py
> cache: Don't run mock as sudo

- planex/util.py
- pylintrc
> util: Use the standard logging library in run

- planex.spec
- planex/cache.py
- planex/depend.py
- planex/fetch.py
- planex/pin.py
- planex/planex.bash
- requirements.txt
- setup.py
> Add bash completion for all entry points

- planex/mappkgname.py
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> mappkgname: Non-exhaustive fixes for Jessie

- planex/cache.py
- planex/depend.py
- planex/fetch.py
- planex/init.py
- planex/makedeb.py
- planex/pin.py
- planex/util.py
> Handle SIGINT cleanly

- planex/cache.py
- planex/fetch.py
- planex/pin.py
- planex/util.py
> Consolidate logging options and defaults

- planex/pin.py
> pin: Delete dict of spec pins when all its source pins are removed

- planex/Makefile.rules
> Makefile.rules: Add editor modelines to set the correct filetype

- planex/Makefile.rules
> Makefile.rules: Delete source target if fetch command fails

- CHANGES
- debian/changelog
- planex.spec
Prepare for next release:
* update package contents
* update changelog
* remove old Planex placeholder variables
> Prepare for release 0.7.0

- planex/util.py
> util: Make '-v' a synonym of '--verbose'

- planex/pin.py
> pin: Include the existing release number in the generated release

- planex/cache.py
- planex/fetch.py
- planex/pin.py
- planex/util.py
> util: Add --version to common parser options

- planex/fetch.py
> fetch: Use a temporary file to avoid blatting on error

- planex-demo/README.md
> demo: Update README with handling of external spec files

- planex/cache.py
> cache: Handle --no-loopback-repo to disable the loopback repo

- planex-demo/mock/default.cfg.in
> demo: Don't let mock blow away the chroot on failure

- planex.spec
> planex.spec: Inject version/release release into setup.py before build

- planex/pin.py
> pin: Update pin if base spec file changes

- planex/fetch.py
> fetch: Check downloaded content looks sensible

- planex/fetch.py
Be a little less strict about unknown file extensions
> Filetype detection fixes

- planex/Makefile.rules
- planex/fetch.py
This reverts commit 15cdc0c2b96d2e77185cdeb645b8eec925f326d8.
> fetch: Restore ability to fetch individual sources

- debian/changelog
- planex.spec
> planex: Release 0.7.0

- planex/depend.py
> depend: Add common parser options

- planex/pin.py
> Serialise pins file with pretty-printing

- debian/changelog
- planex.spec
- setup.py
> packaging: Update versions and changelogs for release 0.7.1

- .travis.yml
See http://docs.travis-ci.com/user/migrating-from-legacy
> travis: Switch to new container-based infrastructure

- README.md
> README: Add binary installation instructions

- debian/changelog
- debian/control
- planex/Makefile.rules
- planex/cache.py
- planex/depend.py
- planex/pin.py
- tests/test_depend.py
A variety of small fixes, cleanups and extensions.
> Updates and fixes

- .gitlab-ci.yml
> gitlab: add gitlab-ci.yml

- planex.dot
- planex.ps
> doc: Add graph of Planex workflow

- CHANGES
- debian/changelog
- planex.spec
- setup.py
> packaging: Update versions and changelogs for release 0.7.2

- mk/Makefile
> [cream-bugfix] CA-193263: Install openssl-xs/-wrapper RPMs into mock repo

- build.py
- mk/Makefile
> [tampa-bugfix] CA-193263: Install openssl-xs/-wrapper RPMs into mock repo

- build.py
- mk/Makefile
> CA-193263: Install openssl-xs/-wrapper RPMs into mock repo

- planex/cache.py
- planex/debianchangelog.py
- planex/debiancontrol.py
- planex/debianmisc.py
- planex/debianrules.py
- planex/depend.py
- planex/fetch.py
- planex/pin.py
- planex/util.py
- pylintrc
> Fix wrong-import-order pylint warnings

- planex/spec.py
RPM only considers the 'basename' part of the source URL - the part to
the right of the last /.   This makes it possible to encode a different
local filename for a source file fetched from a remote server, which is
particularly useful when the URL is a CGI script.   For example, the
following source URL will cause RPM to look for a file called
SOURCES/src-1.2.3.tar.gz:
http://example.com/source/query.cgi?param#/src-1.2.3.tar.gz
Before this change, URL fragments were ignored when downloading http://,
https:// and file:// URLS.
> spec: Handle fragments in source URLs correctly

- CHANGES
> CHANGES: Update for release 0.7.3

- planex.spec
- planex/Makefile.rules
- planex/makesrpm.py
- setup.py
Signed-off-by: Salvatore Cambria <salvatore.cambria@citrix.com>
> makesrpm: create a wrapper around rpmbuild

- mk/Makefile
Signed-off-by: Phus Lu <phus.lu@citrix.com>
> CA-202375: Build stunnel-4.15 against openssl-xs-devel-1.0.1e

- planex.spec
> spec: Add runtime dependencies on make and git

- planex.spec
> spec: Makefile.rules is no longer installed to /usr/share/planex

- planex/cache.py
- planex/util.py
> cache, util: Fix pylint import-order warning

- planex/Makefile.rules
> Makefile.rules: Only build quietly if QUIET is defined

- planex/Makefile.rules
> Makefile.rules: Only suppress echoing commands is QUIET is defined

- planex/cache.py
- planex/fetch.py
- planex/pin.py
- planex/util.py
> cache, fetch, pin, util: Fix pylint import-order warnings

- CHANGES
- debian/changelog
- docker/build-container.sh
- docker/wrap.sh
- planex.spec
- setup.py
> Update for release 0.8

- docker/wrap.sh
> docker: Use xenserver/planex image from Docker Hub

- planex/extract.py
Tarballs from GitHub and gitweb have a non-deterministic
top-level. Prepend this directory when extracting files.
> extract: handle archives with generated top-level directories

- planex/depend.py
- planex/fetch.py
> fetch,depend: support ftp

- planex/fetch.py
> fetch: Factor out duplicated lists of supported URL schemes

- Dockerfile
> Dockerfile: Clean up after installing packages to reduce image size

- planex/spec.py
f70e6a discarded all output to stderr, including the cause of
exceptions raised by the rpm module. Redirect output to a file then
print any errors before re-raising exceptions.
> spec: report fatal errors parsing spec file

- planex/Makefile.rules
- planex/depend.py
These flags are no longer used
> depend: Remove --ignore and --ignore-from flags

- planex/makesrpm.py
> make-srpm: Add support for --define parameter

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for release 0.9.0

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for release 0.10.0

- planex/makesrpm.py
We no longer want to intercept a few arguments and pass the others
through to rpmbuild.
> makesrpm: Switch to conventional argument parser

- planex/repository.py
> repository: Handle empty remote_ref gracefully

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 0.11.0 release

- Dockerfile
> Dockerfile: Allow passwordless sudo for the build user

- planex/Makefile.rules
- planex/cmd/depend.py
> Makefile.rules, depend: Make location of pins configurable

- README.md
> README: Remove references to planex-pin and planex-demo

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 0.12.0 release

- planex/cmd/mock.py
In a temporary directory, create a new mock config
based on the config passed in on the command line,
with a suitable loopback Yum repository stanza.
Make sure that the last-modified time of the config
file is the same as that of the input config - if
the config file is newer than the mock chroot cache
then the cache will be rebuilt.   The packages in the
loopback repository are not copied into the mock
cache so it is safe to trick mock into not rebuilding
it.  If the original mock config is changed, the cache
will be rebuilt correctly.
Also copy logging.ini and site-defaults.cfg, ensuring
that their last-modified times are preserved.
> mock: Automatically add loopback repository stanza

- planex/Makefile.rules
> Makefile: Do not symlink mock configuration into _build

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 0.14.0 release

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 0.15.0 release

- planex/git.py
> git.py: Add current_branch function

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 0.15.1 release

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 0.16.0 release

- planex/cmd/manifest.py
> manifest: Add sha1 from pinned repos when possible

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 0.18.0 release

- docker/planex-container
> Docker: Refactor SSH_AUTH_SOCK passthrough logic using format()

- planex/cmd/depend.py
> depend: Add option to disable generation of buildrequires dependencies

- planex/Makefile.rules
Signed-off-by: Kostas Ladopoulos <konstantinos.ladopoulos@citrix.com>
> Makefile.rules: Add 'MOCK_EXTRA_FLAGS' variable

- planex/git.py
> git: Capture output of git archive so it can be passed to FileUpdater

- planex/cmd/fetch.py
- planex/cmd/makesrpm.py
- planex/cmd/patchqueue.py
- planex/git.py
> Add gitsha provides to RPM spec if .gitarchive-info is present

- planex/cmd/mock.py
mock behaves [differently](https://github.com/rpm-software-management/mock/blob/c59581ac78098b2b58b3a30a4a5d1f7338017e6b/py/mockbuild/util.py#L944) whether stderr is a tty or not.
`make output-sync=target` redirects the output, so that stderr is no longer a tty, causing the loss of build output.
Restore mock loglevel to normal, and use `pty.spawn` to turn mock's stderr into a pseudo-tty.
For compatibility with python2.7 explicitly check the exitcode of the child process, because we want to propagate build errors to the parent process.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>
> mock: ensure that build output is always visible

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 0.22.1 release

- planex/git.py
- planex/repository.py
- planex/util.py
- tests/test_manifest.py
- tests/test_repository.py
> git: Move 'git_ls_repository' from planex.utils to planex.git

- planex/cmd/clone.py
- planex/cmd/depend.py
- planex/cmd/init.py
- planex/cmd/makesrpm.py
- planex/cmd/manifest.py
- planex/cmd/mock.py
- planex/cmd/patchqueue.py
- planex/spec.py
> python3: Use the print() function everywhere

- planex/cmd/createmockconfig.py
Allow values in the config_opt dictionary to be defined or overridden
from the command line.
> create-mock-config: add --config_opt argument

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 2.0.0 release

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 2.0.1 release

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 2.1.0 release

- CHANGES
- planex.spec
- setup.py
> Prepare for 2.0.2 release

- planex/cmd/createmockconfig.py
Backport of change by euanh and simonr allowing packages to be explicitly included or excluded from selection criteria
> backport of change to specify packages

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 2.1.1 release

- Dockerfile
This should reduce the chances to hit the docker bug.
Also call yum clean all all the times to remove the yum cache
and avoid additional docker issues.
> Dockerfile: move yum-plugin-ovl install stage on top

- planex/cmd/createmockconfig.py
- test-requirements.txt
- tests/test_createmockconfig.py
Signed-off-by: Kun Ma <kun.ma@citrix.com>
> CP-26319: Add None type check for enablerepo & disablerepo 

- Dockerfile
> Dockerfile: use latest centos

- CHANGES
- planex.spec
- setup.py
> planex: Prepare for 2.2.0 release

- tests/specs/SPECS/N.spec
- tests/specs/SPECS/PQ.lnk
- tests/specs/SPECS/PQ.spec
- tests/specs/SPECS/RP.lnk
- tests/specs/SPECS/RP.spec
Depend on xenserver/nsource, which is ready at:
https://github.com/xenserver/nsource
Signed-off-by: kun ma <kun.ma@citrix.com>
> CP-26570: Reduce planex testing build complex

- planex/spec.py
> spec: Remove unnecessary result variable in source_paths()

- planex/cmd/fetch.py
- planex/spec.py
planex-fetch accepts multiple source arguments and there is code to
download them, but we only ever download one source at a time.
> fetch: Remove unused code to fetch multiple sources

- planex/link.py
> link: Fix typos

- planex/cmd/pin.py
> pin: use sys.exit to also print the error message

- planex/spec.py
- tests/test_spec.py
> spec: Rename File and GitArchive to Blob and GitBlob

- .gitignore
- planex/link.py
- planex/spec.py
- tests/data/ocaml-cstruct.lnk
- tests/test_spec.py
> Follow spec file sourcenames semantics in link files

- README.md
> README: Replace outdated installation instructions with Pip

- README.md
> README: High level overview of links and pins

- README.md
> README: Add a section on design principles

- .travis.yml
- planex/cmd/fetch.py
> fetch.py: replace pycurl with requests

- planex/link.py
- planex/spec.py
- tests/test_patchqueue.py
> Add ignore-autosetup to link files and re-enable autosetup check for patches

- CHANGES
- planex.spec
- setup.py
> Prepare to release 4.0.0beta1

- planex/cmd/depend.py
- tests/test_depend.py
This also adds an option to display the dependency graph as a json object
> Minor refactoring of planex-depend

- CHANGES
- planex.spec
- setup.py
> Prepare to release 4.0.0b2

- planex/cmd/manifest.py
- tests/data/manifest/blktap.json
- tests/data/manifest/branding-xenserver.json
- tests/data/manifest/vhostmd.json
This will help parsing the new format
> Add schemaVersion for manifests

- planex/cmd/manifest.py
URLs and the computed sha1, if any, are the only potentially
useful informations in the manifests. All the rest is more
for debugging purposes.
> manifest.py: expand macros on the urls

- CHANGES
- planex.spec
- setup.py
> Prepare to release 4.0.0beta3

- planex/cmd/fetch.py
- planex/cmd/makesrpm.py
Archives and Patchqueues are already unpacked when considering the sources
> makesrpm.py: use resources for computing the manifests

- planex/cmd/clone.py
This leaves the repatched flow unimplemented, will come in a separate PR
> planex-clone: new cli and preliminary refactoring

- planex/blobs.py
- planex/cmd/fetch.py
- planex/cmd/pin.py
- planex/repository.py
> Fix urlparse imports for python3 compatibility

- planex/cmd/pin.py
> pin: simplify repo_or_path()

- planex/cmd/pin.py
> pin: create output directory if it does not exist

- planex/cmd/clone.py
planex-clone output a .groovy syntax file onto the command line and now
instead outputs a json file to be consumed by the build object in the
new pipelines
> CP-28152 replace planex jenkins file with json

- planex/blobs.py
- planex/cmd/clone.py
- planex/cmd/fetch.py
- planex/cmd/pin.py
Various improvements to make the usual developer workflows not require unnecessary arguments or resources.
> Simplify dev workflow

- planex/cmd/clone.py
Used to state where to put clone_json if alternate location would be
preferred, also defaults to . so it writes config file to pwd
> CP-28152 add output option to planex-clone

- planex/cmd/clone.py
Groovy file output is required to use planex in existing pipelines,
restore this and check for existence of credentials argument
> CP-28152 Restore groovy file output

- planex/cmd/clone.py
> clone: fix destination for Groovy clone

- planex/cmd/clone.py
When the --jenkins argument is given the output should only contain
the final repository, e.g. the patchqueue.
Refactor to simplify the Jenkins vs clone usecases.
> clone: Jenkins form should only process terminal resource

- planex.spec
> Prepare to release 4.1.0beta2

- planex.spec
- planex/cmd/clone.py
> Add dependency for pathlib

- planex/cmd/pin.py
Quality-of-life improvements for planex-pin. To show the current state
of a pin, use "planex-pin --show <package>", and to remove a pin, use
"planex-pin --unpin <package>".
This removes one need for the user to know the implementation of pins.
> Add "show" and "unpin" options to planex-pin

- planex/cmd/clone.py
> CA-308890: clone to paths based on repo name not package

- planex/cmd/fetch.py
- planex/config.py
> CP-30941: allow planex-fetch to apply additional headers from planexrc

- planex/cmd/clone.py
- planex/cmd/depend.py
- planex/cmd/pin.py
Prevent trailing whitespace in json files
> CA-307837 Whitespace issues

- planex/cmd/fetch.py
> CA-314172: make headers host specific

- planex/cmd/fetch.py
- planex/repository.py
- planex/util.py
- tests/test_repository.py
> CA-314198: enumerate the dictionary keys and use REST to get SHA1.

- .travis.yml
- planex/Makefile.rules
> Add timestamps to make rules
